# Generated by Django 4.0.5 on 2022-07-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Заголовок', help_text='<small class="text-muted">Заголовок</small><hr><br>', max_length=250, null=True, verbose_name='Заголовок:')),
                ('image', models.ImageField(blank=True, default='img/default.jpg', help_text='<small class="text-muted">Изображение</small><hr><br>', null=True, upload_to='img/receipt', verbose_name='Изображение:')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('title',),
            },
        ),
    ]
